const ActionTypes = {
    GET_ARTIST: 'GET_ARTIST',
    GET_ARTIST_TRACKS: 'GET_ARTIST_TRACKS',    
    GET_TOP_TRACKS: 'GET_TOP_TRACKS',
    GET_TOP_ARTISTS: 'GET_TOP_ARTISTS',
    GET_ALBUMS: 'GET_ALBUMS',
    GET_ALBUM_TRACKS: 'GET_ALBUM_TRACKS',
    GET_ALBUM: 'GET_ALBUM',
};

export default ActionTypes;